name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_simu:
    env:
      target: simu 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check ${{env.target}} build
      run: |
        git submodule update --init
        cd sources
        mkdir -p _build_${target}
        cd _build_${target}
        cmake .. -DCMAKE_BUILD_TYPE=Release -DTARGET=${target}
        make -j$(nproc)

  build_recovid_revB:
    env:
      target: recovid_revB
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'

    - name: Check recovid_revB build
      run: |
        git submodule update --init
        cd sources
        target=recovid_revB
        mkdir -p _build_${target}
        cd _build_${target}
        cmake .. -DCMAKE_BUILD_TYPE=Release -DTARGET=${target}
        make -j$(nproc) Controller.${target}.elf

    - name: Upload recovid_revB binaries
      uses: actions/upload-artifact@v2-preview
      with:
        name: recovid_revB_binaries
        path: Controller/_build_${{env.target}}/*.elf
